Project1
dolmitya/tinkoff_curs pull request #3
Opened 2023-10-18 11:30 UTC by dolmitya

2023-11-03 00:19 UTC, VictorMinsky requested changes
Добавь меня, пожалуйста, в контрибьюторы репозитория, чтобы я мог резолвить треды с замечаниями.

Гайд -- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/hw1/EvenArrayUtils.java
У меня пару замечаний к структуре твоей репы и коммитам:
1) Репу стоит назвать как-то правильно, всё-таки она теперь у тебя не только для hw1
2) Нет смысла называть коммиты как дата + время, это и так можно посмотреть в их метаинформации. Вообще существует целый гайд по названию -- https://www.conventionalcommits.org/en/v1.0.0/

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +    private Scanner scanner;
final

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +    private PrintStream stream;
final

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +@SuppressWarnings("RegexpSinglelineJava")
Стоит действительно использовать логгер. Убери сапресс

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +                System.out.print(">Input correct letter:\n<");
А не проще ли использовать почти везде println?

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +                    System.out.print("\n>You lost!");
После проигрыша я не увидел слово, а очень хотелось

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/RandomWordSelector.java
> +    private final static org.apache.logging.log4j.Logger LOGGER = LogManager.getLogger();
unused

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/WordMask.java
> +    private final static org.apache.logging.log4j.Logger LOGGER = LogManager.getLogger();
unused

2023-11-03 00:19 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +    private Scanner scanner;
Сначала идут поля класса, потом конструкторы, потом методы. Замечание ко всем файлам

2023-11-05 14:07 UTC, dolmitya commented on src/main/java/edu/project1/Game.java
> +@SuppressWarnings("RegexpSinglelineJava")
Иногда для тестов использую поток System.out, поэтому не выйдет просто его заменить на логгер

2023-11-05 14:08 UTC, dolmitya commented on src/main/java/edu/project1/Game.java
> +                System.out.print(">Input correct letter:\n<");
Гитхаб и идея видят print('\n') и println() разным количеством символов, что ломает тесты

2023-11-05 23:14 UTC, VictorMinsky commented on src/main/java/edu/hw1/EvenArrayUtils.java
Молодец, пофиксил!
Ещё хорошей практикой является отписываться в каждый ишью, даже если это просто `fixed` или что-то более развёрнутое

2023-11-05 23:21 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +                System.out.print(">Input correct letter:\n<");
Правильно. Потому что `\n` -- платформенно зависимый перенос (под UNIX). На винде у тебя `\r\n` -- 2 символа. Стоит поэтому использовать println(), который под капотом использует `System.lineSeparator()` -- из названия думаю понятно, что он делает

2023-11-05 23:21 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +                System.out.print(">Input correct letter:\n<");
Здесь можешь не переписывать, но в будущем старайся использовать методы, которые выдают переносы под платформу, а не ручной `\n`

2023-11-05 23:23 UTC, VictorMinsky commented on src/main/java/edu/project1/Game.java
> +@SuppressWarnings("RegexpSinglelineJava")
Поэтому стоит везде использовать логгер. В продовой разработке практически 0% использования дефолтного принта, т.к. у тебя ни таймстампа нет, ни какой-то доп.информаци.

2023-11-05 23:25 UTC, VictorMinsky approved these changes
OK

2023-11-19 19:58 UTC, merged