Hw4
dolmitya/tinkoff_curs pull request #6
Opened 2023-10-31 22:15 UTC by dolmitya

2023-11-12 22:04 UTC, VictorMinsky requested changes

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/ValidationError.java
> +    private String errorMessage;
unused

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/ValidationError.java
> +        }
Закидывай ошибки в список, а потом просто сделай `join` через запятую

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +    //Отсортировать животных по росту от самого маленького к
Хорош, ещё бы сам номер)

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        List<Animal> result = animals.stream()
Заинлайнь везде переменные

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +                return 0;
`Comparator.comparingInt(Animal::height)`

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +                return 0;
`Comparator.comparing(Animal::weight).reversed()`

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        }
Перепиши на стримы. В помощь `collect` + `Collectors.toMap`

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        return (k > 0 && k < list.size()) ? list.get(k) : null;
Перепиши на стримы. В помощь `sorted`, `skip`, `findFirst`

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        return animals.stream().filter(animal -> animal.age() != animal.paws()).toList();
В стримах операции обычно пишут с новой строки, сделай так везде

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        final int MAX_HEIGHT = 100;
В поле класса

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        return animals.stream().filter(animal -> animal.name().indexOf(' ') > -1).toList();
В помощь `filter` + `split`. В твоём варианте может быть слово + пробел в конце

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +        }
Перепиши на стримы. В помощь `Arrays.stream(...)`, `flatMap`

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +    public Animal task18(List<List<Animal>> animals) {
Используй `List<Animal>... animals`

2023-11-12 22:04 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +    }
У тебя эта функция очень похожа на предыдущую, копипаста. Вынеси как-то общий код или перееиспользуй 19ую функцию

2023-11-19 21:49 UTC, dolmitya commented on src/main/java/edu/hw4/Task.java
> +    //Отсортировать животных по росту от самого маленького к
добавил

2023-11-19 21:51 UTC, dolmitya commented on src/main/java/edu/hw4/Task.java
> +    }
Не знаю, как это реализовать. Только если функцию отдельную куда в параметрах надо строчками подавать check или checkUpdate, но такое выглядит сомнительно.

2023-11-19 21:52 UTC, dolmitya commented on src/main/java/edu/hw4/ValidationError.java
> +    private String errorMessage;
вроде как, теперь используется

2023-11-21 06:31 UTC, VictorMinsky commented on src/main/java/edu/hw4/Task.java
> +    }
Кажется, что 20 задание это 19 задание + просто сделать джоин всего значения (`Set<ValidationError>`) для ключа в строку. Так что вынести точно можно было

2023-11-21 06:31 UTC, VictorMinsky approved these changes
OK

2023-12-10 17:27 UTC, merged